#!/bin/bash
set -e

install_brew_package() {
  local package=$1

  echo "Checking if $package is installed..."

  if ! brew list --formula | grep -q "^$package$"; then
    echo "$package is not installed. Installing..."
    brew install "$package"
  else
      echo "$package is already installed. Upgrading..."
      brew upgrade "$package"
  fi

  echo "---------------------------------"
}

if ! xcode-select -p &> /dev/null; then
    echo "Command Line Tools are not installed. Installing..."
    xcode-select --install
else
    echo "Command Line Tools are already installed."
fi
echo "---------------------------------"

if ! command -v brew &> /dev/null; then
    echo "Homebrew is not installed. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "Homebrew is now installed and ready to use. Checking for updates..."
    brew update
else
    echo "Homebrew is already installed. Updating..."
    brew update
fi
echo "---------------------------------"

PACKAGES=(
  "kubectl"
  "Azure/kubelogin/kubelogin"
  "helm"
  "azure-cli"
  "snyk"
  "gh"
  "yq"
)

for package in "${PACKAGES[@]}"; do
    install_brew_package "$package"
    
    # Special handling for Snyk CLI
    if [ "$package" == "snyk" ]; then
        brew tap snyk/tap
    fi

done

echo "Checking for outdated packages..."
brew outdated
echo "Updating outdated packages..."
echo "All packages installed via Homebrew are up to date."
echo "All required packages/software for FFC development have now been installed."