#!/bin/bash
set -e

echo "BEGIN CHECKING VERSION OF ALL MANDATORY PACKAGES"
echo "---------------------------------"

check_package_version() {
  local package=$1

  echo "Checking version of $package..."
  if command -v "$package" &> /dev/null; then
    case "$package" in
      kubectl) kubectl version --client ;;
      helm) helm version ;;
      *) "$package" --version ;;
    esac
    echo "---------------------------------"
  else
    echo "$package is not installed."
  fi
}

PACKAGES=(
  "brew"
  "kubectl"
  "kubelogin"
  "helm"
  "az"
  "snyk"
  "gh"
  "python3"
  "pip3"
  "pre-commit"
  "detect-secrets"
  "yq"
)

for package in "${PACKAGES[@]}"; do
  check_package_version "$package"
done

echo "END"