#!/bin/bash

set -e

echo "Available commands for dfcp-mac-scripts"
echo ""
echo "---------------------------------------------------------------------------------------------------------------------------------"
echo "Command   |   Description"
echo "---------------------------------------------------------------------------------------------------------------------------------"
echo "./help       - List all available commands for dfcp-mac-scripts"
echo "./install    - Install required packages for FCP development"
echo "./version    - Check versions of packages (only applied to packaged listed in the install script)"
echo "./optional   - Yes/no prompts to install optional packages useful for day-to-day development"
echo "./update     - Update Homebrew and packages"
echo "---------------------------------------------------------------------------------------------------------------------------------"
echo ""
echo "For more details, please refer to the README: https://github.com/rtasalem/dfcp-mac-scripts."
echo "If you experience any bugs or have a feature request, please raise an issue: https://github.com/rtasalem/dfcp-mac-scripts/issues."
