#!/bin/bash
set -e

echo "Defra FFC Mac Scripts - Help"
echo "----------------------------"
echo ""
echo "Available commands:"
echo "  ./help       - List all available commands for dffc-mac-scripts"
echo "  ./mandatory  - Install required packages for FFC development"
echo "  ./version    - Check installed versions of mandatory packages"
echo "  ./optional   - Yes/no prompts to install optional packages useful for day-to-day development"
echo "  ./update     - Update Homebrew and installed packages"
echo ""
echo "For more details, please refer to the README: https://github.com/rtasalem/dffc-mac-scripts."
