#!/bin/bash
set -e

echo "BEGIN INSTALL OF MANDATORY PACKAGES"
echo "---------------------------------"

install_package() {
  local package=$1

  echo "Checking if $package is installed..."

  if ! brew list --formula | grep -q "^$package$"; then
    echo "$package is not installed. Installing..."
    brew install "$package" >/dev/null 2>&1
    echo "$package installation complete."
  else
      echo "$package is already installed. Upgrading..."
      brew upgrade "$package" >/dev/null 2>&1
  fi

  echo "---------------------------------"
}

install_cask() {
  local cask=$1

  echo "Checking if $cask is installed..."

  if ! brew list --cask | grep -q "^$cask$"; then
      echo "$cask is not installed. Installing..."
      brew install --cask "$cask" >/dev/null 2>&1
      echo "$cask installation complete."
  else
      echo "$cask is already installed. Upgrading..."
      brew upgrade --cask "$cask" >/dev/null 2>&1
  fi

  echo "---------------------------------"
}

if ! xcode-select -p &> /dev/null; then
    echo "Command Line Tools are not installed. Installing..."
    xcode-select --install
else
    echo "Command Line Tools are already installed."
fi
echo "---------------------------------"

if ! command -v brew &> /dev/null; then
    echo "Homebrew is not installed. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "Homebrew is now installed and ready to use. Checking for updates..."
    brew update
else
    echo "Homebrew is already installed. Updating..."
    brew update
fi
echo "---------------------------------"

PACKAGES=(
  "azure-cli"
  "Azure/kubelogin/kubelogin"
  "detect-secrets"
  "gh"
  "helm"
  "kubectl"
  "openjdk"
  "pre-commit"
  "python"
  "snyk"
)

CASKS=(
  "docker"
  "dotnet-sdk"
  "visual-studio-code"
)

for package in "${PACKAGES[@]}"; do
  install_package "$package"
  
  # Special handling for Snyk CLI
  if [ "$package" == "snyk" ]; then
      brew tap snyk/tap
  fi
done

for cask in "${CASKS[@]}"; do
    install_cask "$cask"
done

echo "Checking for outdated packages..."
brew outdated || true
echo "Updating outdated packages..."
echo "All packages installed via Homebrew are up to date."

echo "Required packages/software for FFC development have now been installed."
echo "DISCLAIMER: packges/software not covered in this scripts includes NVM (Node Version Manager) and neostandard"
echo "Please refer to the FFC Development Guide for instructions: https://github.com/DEFRA/ffc-development-guide/blob/main/docs/local-development-setup/index.md"

echo "END"