#!/bin/bash
set -e

# VS CODE

echo "Installing Visual Studio Code via Homebrew..."
brew install --cask visual-studio-code
echo "VS Code is now installed."
echo "---------------------------------"

# DOCKER DESKTOP

echo "Installing Docker Desktop via Homebrew..."
brew install --cask docker
echo "Docker Desktop is now installed."
echo "---------------------------------"

# POSTMAN

read -p "Do you want to install Postman? [y/n]: " install_postman

if [[ $install_postman == "y" ]]; then
  echo "Installing Postman via Homebrew..."
  brew install --cask postman
  echo "Postman is now installed."
  echo "---------------------------------"
fi

# LENS

read -p "Do you want to install Lens? [y/n]: " install_lens

if [[ $install_lens == "y" ]]; then
  echo "Installing Lens via Homebrew..."
  brew install --cask lens
  echo "Lens is now installed."
  echo "---------------------------------"
fi

# AZURE DATA STUDIO

read -p "Do you want to install Azure Data Studio? [y/n]: " install_azure_data_studio

if [[ $install_azure_data_studio == "y" ]]; then
  echo "Installing Azure Data Studio via Homebrew..."
  brew install --cask azure-data-studio
  echo "Azure Data Studio is now installed."
  echo "---------------------------------"
fi

# MICROSOFT AZURE STORAGE EXPLORER

read -p "Do you want to install Microsoft Azure Storage Explorer? [y/n]: " install_azure_storage_explorer

if [[ $install_azure_storage_explorer == "y" ]]; then
  echo "Installing Microsoft Azure Storage Explorer via Homebrew..."
  brew install --cask microsoft-azure-storage-explorer
  echo "Microsoft Azure Storage Explorer is now installed."
  echo "---------------------------------"
fi

# PGADMIN 4

read -p "Do you want to install pgAdmin 4? [y/n]: " install_pgadmin

if [[ $install_pgadmin == "y" ]]; then
  echo "Installing pgAdmin 4 via Homebrew..."
  brew install --cask pgadmin4
  echo "pgAdmin 4 is now installed."
  echo "---------------------------------"
fi

# SLACK

read -p "Do you want to install Slack? [y/n]: " install_slack

if [[ $install_slack == "y" ]]; then
  echo "Installing Slack via Homebrew..."
  brew install --cask slack
  echo "Slack is now installed."
  echo "---------------------------------"
fi

# OBSIDIAN

read -p "Do you want to install Obsidian? [y/n]: " install_obsidian

if [[ $install_obsidian == "y" ]]; then
  echo "Installing Obsidian via Homebrew..."
  brew install --cask obsidian
  echo "Obsidian is now installed."
  echo "---------------------------------"
fi

# DRAW.IO

read -p "Do you want to install draw.io? [y/n]: " install_drawio

if [[ $install_drawio == "y" ]]; then
  echo "Installing draw.io via Homebrew..."
  brew install --cask drawio
  echo "draw.io is now installed."
  echo "---------------------------------"
fi