#!/bin/bash
set -e

# PYTHON3 & PIP3

echo "Installing Python & pip using Homebrew..."
brew install python
echo "Python & pip are now installed. Checking version of Python & pip..."
python3 --version
pip3 --version
echo "---------------------------------"

# PRE-COMMIT

echo "Installing pre-commit using Homebrew..."
brew install pre-commit
echo "Pre-commit is now installed. Checking version of pre-commit..."
pre-commit --version
echo "---------------------------------"

# DETECT-SECRETS

echo "Installing detect-secrets using Homebrew..."
brew install detect-secrets
echo "Detect-secrets is now installed. Checking version of detect-secrets..."
detect-secrets --version