#!/bin/bash
set -e

echo "BEGIN INSTALL OF MANDATORY PACKAGES"
echo "---------------------------------"

if ! xcode-select -p &> /dev/null; then
    echo "Command Line Tools are not installed. Installing..."
    xcode-select --install
else
    echo "Command Line Tools are already installed."
fi
echo "---------------------------------"

if ! command -v brew &> /dev/null; then
    echo "Homebrew is not installed. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "Homebrew is now installed and ready to use. Checking for updates..."
    brew update
else
    echo "Homebrew is already installed. Updating..."
    brew update
fi
echo "---------------------------------"

FORMULAE=(
  "kubectl"
  "Azure/kubelogin/kubelogin"
  "helm"
  "azure-cli"
  "snyk"
  "gh"
  "python"
  "pre-commit"
  "detect-secrets"
)

CASKS=(
  "dotnet-sdk"
  "visual-studio-code"
  "docker"
)

for formula in "${FORMULAE[@]}"; do
  brew install "$formula"
  
  # Special handling for Snyk CLI
  if [ "$package" == "snyk" ]; then
      brew tap snyk/tap
  fi
done

for cask in "${CASKS[@]}"; do
    brew install --cask "$cask"
done

echo "Checking for outdated packages..."
brew outdated || true
echo "Updating outdated packages..."
echo "All packages installed via Homebrew are up to date."

echo "Required packages/software for FFC development have now been installed."
echo "DISCLAIMER: packges/software not covered in this scripts includes NVM (Node Version Manager), StandardJS, and .NET SDK."
echo "Please refer to the FFC Development Guide for instructions: https://github.com/DEFRA/ffc-development-guide/blob/main/docs/local-development-setup/index.md"

echo "END"
#wwgee