#!/bin/bash

set -e

install_optional_formula() {
  local formula=$1

  echo "Checking if $formula is installed..."

  if ! brew list --formula | grep -q "^$formula$"; then
      echo "$formula is not installed. Installing..."
      brew install "$formula"
      echo "$formula installation complete."
  else
      echo "$formula is already installed. Upgrading..."
      brew upgrade "$formula"
  fi

  echo "---------------------------------"
}

install_optional_cask() {
  local cask=$1

  echo "Checking if $cask is installed..."

  if ! brew list --cask | grep -q "^$cask$"; then
      echo "$cask is not installed. Installing..."
      brew install --cask "$cask"
      echo "$cask installation complete."
  else
      echo "$cask is already installed. Upgrading..."
      brew upgrade --cask "$cask"
  fi

  echo "---------------------------------"
}

OPTIONAL_FORMULAE=(
  "k9s"
  "mongosh"
  "postgresql@14"
  "yq"
)

OPTIONAL_CASKS=(
  "azure-data-studio"
  "drawio"
  "ghostty"
  "google-chrome"
  "lens"
  "microsoft-azure-storage-explorer"
  "microsoft-outlook"
  "microsoft-teams"
  "mongodb-compass"
  "obsidian"
  "pgadmin4"
  "postman"
  "slack"
  "warp"
)

for formula in "${OPTIONAL_FORMULAE[@]}"; do

  read -p "Do you want to install $formula? [y/n]: " response

  if [[ $response == "y" ]]; then
    install_optional_formula "$formula"
  fi

done

for cask in "${OPTIONAL_CASKS[@]}"; do

  read -p "Do you want to install $cask? [y/n]: " response
  
  if [[ $response == "y" ]]; then
    install_optional_cask "$cask"
  fi

done
