#!/bin/bash

set -e

install_optional_cask() {
  local cask=$1

  echo "Checking if $cask is installed..."

  if ! brew list --cask | grep -q "^$cask$"; then
      echo "$cask is not installed. Installing..."
      brew install --cask "$cask"
      echo "$cask installation complete."
  else
      echo "$cask is already installed. Upgrading..."
      brew upgrade --cask "$cask"
  fi

  echo "---------------------------------"
}

OPTIONAL_CASKS=(
  "microsoft-outlook"
  "microsoft-teams"
  "mongodb-compass"
  "slack"
)

for cask in "${OPTIONAL_CASKS[@]}"; do

  read -p "Do you want to install $cask? [y/n]: " response
  
  if [[ $response == "y" ]]; then
    install_optional_cask "$cask"
  fi

done
