#!/bin/bash

set -e

check_package_version() {
  local package=$1

  echo "Checking version of $package..."
  if command -v "$package" &> /dev/null; then
    "$package" --version
    echo "---------------------------------"
  else
    echo "$package is not installed."
  fi
}

PACKAGES=(
  "aws"
  "brew"
  "detect-secrets"
  "gh"
  "java"
  "mongosh"
  "pip3"
  "pre-commit"
  "python3"
  "snyk"
)

for package in "${PACKAGES[@]}"; do
  check_package_version "$package"
done
